#
# Copyright (C) 2019 IBM Corporation.
#
# Authors:
# Frederico Araujo <frederico.araujo@ibm.com>
# Teryl Taylor <terylt@ibm.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Template values for sysflowagent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry:
  secretName: ""

# sysflow collection probe parameters
sfcollector:
  # Comment out if you always want to pull images 
  imagePullPolicy: IfNotPresent
  # image repository
  repository: sysflowtelemetry/sf-collector
  # image tag
  tag: 0.2.2
  # timeout in seconds to start roll a new trace files
  interval: 60
  # output directory, where traces are written to inside container
  outDir: /mnt/data/
  # collection filter
  filter: "\"container.type!=host and container.name!=sfexporter and container.name!=sfcollector\""
  # Use this criPath if running docker runtime
  criPath: ""
  # Use this criPath if running containerd runtime
  #criPath: "/var/run/containerd/containerd.sock"
  # Use this criPath if running crio runtime
  #criPath: "/var/run/crio/crio.sock"
  # enable drop mode removes syscalls inside the kernel before they are passed up to the collector
  # results in much better performance, less drops, but does remove mmaps from output
  dropMode: true
  # filters out any descriptor that is not a file, including unix sockets and pipes
  fileOnly: false
  # enables the creation of process flows
  procFlow: false
  # sets mode for reads: "0" enables recording all file reads as flows.  "1" disables all file reads.
  # "2" disables recording file reads to noisy directories: "/proc/", "/dev/", "/sys/", "//sys/",
  # "/lib/",  "/lib64/", "/usr/lib/", "/usr/lib64/"
  readMode: "0"
  # enables ebpf probe (required for minikube)
  ebpf: true
  # mounts /etc directory in container (required for minikube and Google COS)
  mountEtc: true
  # k8s API URL
  k8sAPIURL: "http://localhost:8001"
  # k8s API Cert
  #k8sAPICert:

# sysflow exporter parameters
sfexporter:
  # Comment out if you always want to pull images 
  imagePullPolicy: IfNotPresent
  # image repository
  repository: sysflowtelemetry/sf-exporter
  # image tag
  tag: latest
  # export inverval
  interval: 30
  # directory where traces are read from inside container
  outDir: /mnt/data/
  # object store address (overridden by install script)
  s3Endpoint: "<ip address>"
  # object store port
  s3Port: 9000
  # object store bucket where to push traces
  s3Bucket: "<s3 bucket>"
  # object store location (overridden by install script)
  s3Location:  "<s3 region>"
  # object store access key (overridden by install script)
  s3AccessKey: "<s3_access_key>"
  # object store secret key (overridden by install script)
  s3SecretKey: "<s3_secret_key>"
  # object store connection, 'true' if TLS-enabled, 'false' otherwise
  s3Secure: "false"

#nameOverride: "sfexporter"
#fullnameOverride: ""
tmpfsSize: 500Mi # size of tmpfs shared volume between collector and exporter (where traces are written)

## @param resources - object - optional
## Resource requests and limits for the kube-state-metrics container.
#
resources: {}
#  requests:
#    cpu: 600m
#    memory: 512Mi
#  limits:
#    cpu: 2000m
#    memory: 1536Mi
   
## @param nodeSelector - object - optional
## Allow the ClusterChecks Deployment to schedule on selected nodes
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
#
# nodeSelector: {}

## @param tolerations - array - required
## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
#
# tolerations: []

## @param affinity - object - optional
## Allow the ClusterChecks Deployment to schedule using affinity rules.
## By default, ClusterChecks Deployment Pods are forced to run on different Nodes.
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
#
# affinity: {}
